<?php

    /*!
     * ifsoft.co.uk v1.0
     *
     * http://ifsoft.com.ua, http://ifsoft.co.uk
     * raccoonsquare@gmail.com
     *
     * Copyright 2012-2018 Demyanchuk Dmitry (raccoonsquare@gmail.com)
     */

$C['GCM_NOTIFY_VIDEO_COMMENT_REPLY'] = 21;
$C['GCM_NOTIFY_VIDEO_COMMENT'] = 22;
$C['GCM_NOTIFY_VIDEO_LIKE'] = 23;

$C['GCM_NOTIFY_REFERRAL'] = 24;

$C['GCM_NOTIFY_MATCH'] = 25;

$C['GCM_NOTIFY_TYPING_START'] = 27;
$C['GCM_NOTIFY_TYPING_END'] = 28;

$C['GCM_NOTIFY_MEDIA_APPROVE'] = 1001;
$C['GCM_NOTIFY_MEDIA_REJECT'] = 1002;
$C['GCM_NOTIFY_PROFILE_PHOTO_APPROVE'] = 1003;
$C['GCM_NOTIFY_PROFILE_PHOTO_REJECT'] = 1004;
$C['GCM_NOTIFY_ACCOUNT_APPROVE'] = 1005;
$C['GCM_NOTIFY_ACCOUNT_REJECT'] = 1006;

$C['NOTIFY_TYPE_MEDIA_APPROVE'] = 10;
$C['NOTIFY_TYPE_MEDIA_REJECT'] = 11;
$C['NOTIFY_TYPE_PROFILE_PHOTO_APPROVE'] = 12;
$C['NOTIFY_TYPE_PROFILE_PHOTO_REJECT'] = 13;
$C['NOTIFY_TYPE_ACCOUNT_APPROVE'] = 14;
$C['NOTIFY_TYPE_ACCOUNT_REJECT'] = 15;